# Use root/example as user/password credentials
version: '3.7'

services:
  app:
    container_name: boilerplate-test
    build:
      context: .
      target: test
    restart: always
    ports:
      - "8080:8080"